# CMake generated Testfile for 
# Source directory: /home/runner/work/eckit/eckit/tests/container
# Build directory: /home/runner/work/eckit/eckit/_codeql_build_dir/tests/container
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(eckit_test_container_sharedmemarray "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_sharedmemarray")
set_tests_properties(eckit_test_container_sharedmemarray PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;1;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_btree "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_btree")
set_tests_properties(eckit_test_container_btree PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;5;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_bloomfilter "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_bloomfilter")
set_tests_properties(eckit_test_container_bloomfilter PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;9;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_trie "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_trie")
set_tests_properties(eckit_test_container_trie PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;13;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_queue "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_queue")
set_tests_properties(eckit_test_container_queue PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;17;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_densemap "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_densemap")
set_tests_properties(eckit_test_container_densemap PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;21;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_denseset "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_denseset")
set_tests_properties(eckit_test_container_denseset PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;25;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_cache_lru "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_cache_lru")
set_tests_properties(eckit_test_container_cache_lru PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;29;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_cachemanager "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_cachemanager")
set_tests_properties(eckit_test_container_cachemanager PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;33;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
add_test(eckit_test_container_benchmark_densemap "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/container/eckit_test_container_benchmark_densemap")
set_tests_properties(eckit_test_container_benchmark_densemap PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;37;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/container/CMakeLists.txt;0;")
