# SPDX-FileCopyrightText: 1996- European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

dependencies: |
  ecmwf/ecbuild
  Deutsches-Klimarechenzentrum/libaec@refs/tags/v1.1.6
dependency_branch: develop
parallelism_factor: 8
