#line 2 "/home/runner/work/eckit/eckit/_codeql_build_dir/src/eckit/cmd/cmdsl.c"

#line 4 "/home/runner/work/eckit/eckit/_codeql_build_dir/src/eckit/cmd/cmdsl.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define eckit_cmd_const const

#if defined(__GNUC__) && __GNUC__ >= 3
#define eckit_cmd_noreturn __attribute__((__noreturn__))
#else
#define eckit_cmd_noreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (eckit_cmd__start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((eckit_cmd__start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE eckit_cmd_restart( eckit_cmd_in  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(eckit_cmd__state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct eckit_cmd__buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t eckit_cmd__size_t;
#endif

extern int eckit_cmd_leng;

extern FILE *eckit_cmd_in, *eckit_cmd_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for eckit_cmd__rule_can_match_eol because it requires
     *       access to the local variable eckit_cmd__act. Since eckit_cmd_less() is a macro, it would break
     *       existing scanners that call eckit_cmd_less() from OUTSIDE eckit_cmd_lex.
     *       One obvious solution it to make eckit_cmd__act a global. I tried that, and saw
     *       a 5% performance hit in a non-eckit_cmd_lineno scanner, because eckit_cmd__act is
     *       normally declared as a  variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int eckit_cmd_l;\
                for ( eckit_cmd_l = n; eckit_cmd_l < eckit_cmd_leng; ++eckit_cmd_l )\
                    if ( eckit_cmd_text[eckit_cmd_l] == '\n' )\
                        --eckit_cmd_lineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = eckit_cmd__cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --eckit_cmd_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define eckit_cmd_less(n) \
	do \
		{ \
		/* Undo effects of setting up eckit_cmd_text. */ \
        int eckit_cmd_less_macro_arg = (n); \
        YY_LESS_LINENO(eckit_cmd_less_macro_arg);\
		*eckit_cmd__cp = (eckit_cmd__hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(eckit_cmd__c_buf_p) = eckit_cmd__cp = eckit_cmd__bp + eckit_cmd_less_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up eckit_cmd_text again */ \
		} \
	while ( 0 )
#define unput(c) eckit_cmd_unput( c, (eckit_cmd_text_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct eckit_cmd__buffer_state
	{
	FILE *eckit_cmd__input_file;

	char *eckit_cmd__ch_buf;		/* input buffer */
	char *eckit_cmd__buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int eckit_cmd__buf_size;

	/* Number of characters read into eckit_cmd__ch_buf, not including EOB
	 * characters.
	 */
	int eckit_cmd__n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int eckit_cmd__is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int eckit_cmd__is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int eckit_cmd__at_bol;

    int eckit_cmd__bs_lineno; /**< The line count. */
    int eckit_cmd__bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int eckit_cmd__fill_buffer;

	int eckit_cmd__buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via eckit_cmd_restart()), so that the user can continue scanning by
	 * just pointing eckit_cmd_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t eckit_cmd__buffer_stack_top = 0; /**< index of top of stack. */
static size_t eckit_cmd__buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * eckit_cmd__buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (eckit_cmd__buffer_stack) \
                          ? (eckit_cmd__buffer_stack)[(eckit_cmd__buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (eckit_cmd__buffer_stack)[(eckit_cmd__buffer_stack_top)]

/* eckit_cmd__hold_char holds the character lost when eckit_cmd_text is formed. */
static char eckit_cmd__hold_char;
static int eckit_cmd__n_chars;		/* number of characters read into eckit_cmd__ch_buf */
int eckit_cmd_leng;

/* Points to current character in buffer. */
static char *eckit_cmd__c_buf_p = NULL;
static int eckit_cmd__init = 0;		/* whether we need to initialize */
static int eckit_cmd__start = 0;	/* start state number */

/* Flag which is used to allow eckit_cmd_wrap()'s to do buffer switches
 * instead of setting up a fresh eckit_cmd_in.  A bit of a hack ...
 */
static int eckit_cmd__did_buffer_switch_on_eof;

void eckit_cmd_restart ( FILE *input_file  );
void eckit_cmd__switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE eckit_cmd__create_buffer ( FILE *file, int size  );
void eckit_cmd__delete_buffer ( YY_BUFFER_STATE b  );
void eckit_cmd__flush_buffer ( YY_BUFFER_STATE b  );
void eckit_cmd_push_buffer_state ( YY_BUFFER_STATE new_buffer  );
void eckit_cmd_pop_buffer_state ( void );

static void eckit_cmd_ensure_buffer_stack ( void );
static void eckit_cmd__load_buffer_state ( void );
static void eckit_cmd__init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER eckit_cmd__flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE eckit_cmd__scan_buffer ( char *base, eckit_cmd__size_t size  );
YY_BUFFER_STATE eckit_cmd__scan_string ( const char *eckit_cmd__str  );
YY_BUFFER_STATE eckit_cmd__scan_bytes ( const char *bytes, int len  );

void *eckit_cmd_alloc ( eckit_cmd__size_t  );
void *eckit_cmd_realloc ( void *, eckit_cmd__size_t  );
void eckit_cmd_free ( void *  );

#define eckit_cmd__new_buffer eckit_cmd__create_buffer
#define eckit_cmd__set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        eckit_cmd_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            eckit_cmd__create_buffer( eckit_cmd_in, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->eckit_cmd__is_interactive = is_interactive; \
	}
#define eckit_cmd__set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        eckit_cmd_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            eckit_cmd__create_buffer( eckit_cmd_in, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->eckit_cmd__at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->eckit_cmd__at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *eckit_cmd_in = NULL, *eckit_cmd_out = NULL;

typedef int eckit_cmd__state_type;

#define YY_FLEX_LEX_COMPAT
extern int eckit_cmd_lineno;
int eckit_cmd_lineno = 1;

extern char eckit_cmd_text[];

static eckit_cmd__state_type eckit_cmd__get_previous_state ( void );
static eckit_cmd__state_type eckit_cmd__try_NUL_trans ( eckit_cmd__state_type current_state  );
static int eckit_cmd__get_next_buffer ( void );
static void eckit_cmd_noreturn eckit_cmd__fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up eckit_cmd_text.
 */
#define YY_DO_BEFORE_ACTION \
	(eckit_cmd_text_ptr) = eckit_cmd__bp; \
	eckit_cmd_leng = (int) (eckit_cmd__cp - eckit_cmd__bp); \
	(eckit_cmd__hold_char) = *eckit_cmd__cp; \
	*eckit_cmd__cp = '\0'; \
	if ( eckit_cmd_leng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	eckit_cmd__flex_strncpy( eckit_cmd_text, (eckit_cmd_text_ptr), eckit_cmd_leng + 1 ); \
	(eckit_cmd__c_buf_p) = eckit_cmd__cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct eckit_cmd__trans_info
	{
	flex_int32_t eckit_cmd__verify;
	flex_int32_t eckit_cmd__nxt;
	};
static const flex_int16_t eckit_cmd__accept[185] =
    {   0,
       51,   51,   51,   51,   55,   53,   51,   52,   21,   10,
       50,    2,   53,    4,   53,   47,   49,   53,   53,    3,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,    1,    5,    6,    9,
       48,    8,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   53,   51,
       14,    2,   12,   46,   47,   47,   49,   16,   17,   13,
       22,    3,   15,   41,   38,   43,   42,   39,   40,   47,
       47,   47,   47,   47,   47,   47,   47,   18,   47,   47,
       47,    1,    1,   48,   48,    7,   41,   38,   43,   42,

       39,   40,   48,   48,   48,   48,   48,   48,   48,   48,
       18,   48,   48,   48,   19,   46,   46,   11,   47,   24,
       47,   47,   47,   47,   20,   47,   47,   47,   11,   48,
       24,   48,   48,   48,   48,   20,   48,   48,   48,   44,
       25,   36,   47,   47,   47,   47,   30,   34,   44,   25,
       36,   48,   48,   48,   48,   30,   34,   45,   37,   23,
       47,   32,   47,   31,   35,   45,   37,   23,   48,   32,
       48,   31,   35,   26,   33,   28,   26,   33,   28,   27,
       29,   27,   29,    0
    } ;

static const YY_CHAR eckit_cmd__ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,    1,    1,    1,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,    1,   19,
       20,   21,    1,    1,   18,   18,   18,   18,   18,   18,
       22,   23,   18,   18,   24,   18,   25,   18,   18,   26,
       18,   18,   18,   27,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   28,    1,   29,   30,   31,   32,

       33,   18,   18,   34,   35,   18,   36,   18,   37,   38,
       39,   18,   18,   40,   41,   42,   43,   18,   44,   18,
       45,   18,    1,   46,    1,   47,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR eckit_cmd__meta[48] =
    {   0,
        1,    1,    1,    2,    1,    2,    1,    2,    1,    1,
        2,    1,    1,    2,    3,    4,    3,    4,    1,    5,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    2,    1
    } ;

static const flex_int16_t eckit_cmd__base[195] =
    {   0,
        0,    0,   47,    0,  160,  661,   93,  661,  136,  661,
      661,    0,  141,  661,    0,   81,  129,   79,   81,  122,
       87,   88,   91,   92,   95,   96,   99,  112,  115,  116,
      119,  123,  124,  128,  132,  135,   89,  661,  661,  661,
      154,  104,  157,  160,  163,  179,  182,  185,  188,  202,
      205,  212,  220,  124,  203,  217,  225,  228,   77,  179,
      661,    0,  661,  169,    0,  191,  103,  661,  661,  661,
      661,   99,  661,  208,  224,  251,  254,  255,  258,  259,
      262,  263,  266,  269,  272,  275,  278,  279,  283,  282,
      288,    0,    0,    0,  277,  661,  289,  290,  292,  297,

      304,  305,  306,  313,  318,  321,  330,  332,  339,  344,
      346,  353,  358,  360,  661,    0,  334,  379,  383,  386,
      389,  390,  393,  396,  397,  400,  405,  408,  389,  411,
      408,  416,  423,  424,  431,  436,  439,  447,  450,  416,
      415,  476,  477,  480,  481,  485,  484,  488,  475,  489,
      491,  502,  504,  513,  515,  516,  527,  491,  492,  504,
      543,  523,  546,  550,  554,  544,  545,  546,  553,  558,
      566,  561,  573,  574,  555,  589,  578,  581,  592,  594,
      607,  597,  599,  661,  637,  111,  639,  642,  646,  648,
      650,  652,  654,  656

    } ;

static const flex_int16_t eckit_cmd__def[195] =
    {   0,
      184,    1,  184,    3,  184,  184,  184,  184,  184,  184,
      184,  185,  184,  184,  186,  187,  184,  184,  184,  188,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  189,  184,  184,  184,
      190,  184,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,   53,   53,   53,   53,   53,  184,  184,
      184,  185,  184,  191,  192,  187,  184,  184,  184,  184,
      184,  188,  184,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  189,  189,  193,   53,  184,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,  184,  194,  191,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,  187,
      187,  187,  187,  187,  187,  187,  187,  187,   53,   53,
       53,   53,   53,   53,   53,   53,   53,  187,  187,  187,
      187,  187,  187,  187,  187,   53,   53,   53,   53,   53,
       53,   53,   53,  187,  187,  187,   53,   53,   53,  187,
      187,   53,   53,    0,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184

    } ;

static const flex_int16_t eckit_cmd__nxt[709] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,    6,   12,   13,
       10,   14,    6,   15,    6,   16,   17,   16,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   16,   27,   28,
       16,   29,   16,   30,   16,   16,   31,   32,   33,   16,
       34,   16,   16,   35,   36,   37,    6,    6,    7,    8,
        7,    9,   10,   11,    6,    6,   13,   10,   38,   39,
        6,    6,   40,   17,   41,   18,   19,   42,   43,   44,
       45,   46,   47,   48,    6,   49,   50,   41,   51,   41,
       52,   41,   41,   53,   54,   55,   41,   56,   41,   41,
       57,   58,   59,    6,   60,   65,   60,   65,   68,   69,

       70,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   64,   65,   74,   75,  184,   67,
       76,   77,  115,   96,   78,   79,   65,   71,   65,   65,
       65,   65,   65,   65,   93,   65,   80,   65,   65,   65,
       65,   73,   65,   82,   65,   67,   65,   84,   65,   65,
       63,   65,   95,   85,   83,   61,   81,   86,   95,  184,
       89,   87,  110,   88,   90,  184,  184,   91,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       60,   94,   60,  116,   94,  116,   97,   94,  184,   98,
       94,  184,   99,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   65,   94,   65,  100,   94,
      184,  101,   94,  184,  102,   94,   94,   94,   94,   94,
       94,   94,   65,  184,   65,  103,   94,   94,   94,   94,
      184,   95,   94,  105,   94,   94,   94,   95,   65,   94,
       65,   95,  111,  184,  184,   95,  104,   94,  107,  112,
      106,   95,  184,   95,  108,   95,   95,  113,  109,   95,
      114,  184,   95,   95,  184,   65,   95,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,  184,   65,   65,  184,   65,   65,  184,   65,   65,
      118,   65,   65,   65,   65,   65,   65,   65,   65,   65,

      184,  184,   65,  119,   65,   95,  184,  120,  121,  123,
      122,   95,  124,  126,  127,   95,  128,   95,   95,  125,
       95,  184,  184,   95,   95,   95,   95,   95,   95,  184,
       95,   95,   95,   95,   95,   95,  184,  129,   95,   95,
       95,   95,   95,   95,   95,  184,   95,   95,  116,   95,
      116,   95,   95,  184,  130,   95,   95,  184,   95,   95,
       95,  184,  131,  132,   95,  184,   95,   95,   95,  134,
       95,  133,   95,   95,   95,  184,  135,   95,   95,  184,
       95,   95,   95,  137,   95,  136,   95,   95,  139,  184,
      138,   95,   95,   65,   95,   65,   95,   65,   95,   65,

       65,  184,   65,   65,   65,   65,   65,   65,  184,   65,
       65,   65,   65,   65,   65,  140,   65,   95,  184,   65,
      143,   65,   65,   95,   65,  184,  141,   95,  142,   65,
       65,   65,   65,  184,  184,  144,   95,  145,  146,   95,
      147,  184,   95,  149,   95,   95,   95,  148,  150,   95,
       95,   95,   95,  152,   95,  151,  158,   95,   95,   95,
      184,   95,   95,  184,   95,   95,  153,   95,  184,   95,
       95,  184,  154,   95,   95,   95,  184,  155,   95,  184,
      184,   95,  156,  184,   95,   95,  184,  184,   95,  157,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   65,   65,   95,   65,   65,   65,   65,   65,   95,
      160,  184,  184,   95,  162,  166,  159,   95,   65,   95,
       65,  161,  163,   95,  164,   95,  184,   95,  165,   95,
       95,  167,   95,  184,  184,  168,   95,   65,   95,   65,
       95,   95,   95,   95,   95,  169,  170,   95,  184,   95,
       95,   95,  171,   95,   95,   95,  172,   65,  184,   65,
       65,   95,   65,  175,   65,   95,   65,  173,   65,   65,
       65,   65,   95,   95,   95,  174,  184,  176,   95,   95,
       95,   95,   95,   95,   95,  177,   95,   95,   65,   95,
       65,   95,   95,  184,   95,   95,   95,  179,  178,   95,

       95,   95,  184,   65,   95,   65,   95,   95,   65,   95,
       65,   95,   95,  184,  180,   95,   95,  184,  182,   95,
       95,   65,  184,   65,  184,   95,   95,   95,  184,  181,
       95,   95,  183,   95,  184,   95,  184,   95,   62,   62,
       62,   66,   66,   72,   72,   72,   72,   92,   92,   92,
       95,   95,  117,  117,   65,   65,   94,   94,  116,  116,
        5,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184
    } ;

static const flex_int16_t eckit_cmd__chk[709] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    7,   16,    7,   16,   18,   18,

       19,   21,   22,   21,   22,   23,   24,   23,   24,   25,
       26,   25,   26,   27,  186,   27,   21,   22,   72,   67,
       23,   24,   59,   42,   25,   26,   28,   19,   28,   29,
       30,   29,   30,   31,   37,   31,   27,   32,   33,   32,
       33,   20,   34,   29,   34,   17,   35,   31,   35,   36,
       13,   36,   54,   31,   30,    9,   28,   31,   54,    5,
       34,   32,   54,   33,   35,    0,    0,   36,   41,   41,
       41,   43,   43,   43,   44,   44,   44,   45,   45,   45,
       60,   41,   60,   64,   43,   64,   43,   44,    0,   44,
       45,    0,   45,   46,   46,   46,   47,   47,   47,   48,

       48,   48,   49,   49,   49,   66,   46,   66,   46,   47,
        0,   47,   48,    0,   48,   49,   50,   50,   50,   51,
       51,   51,   74,    0,   74,   49,   52,   52,   52,   50,
        0,   55,   51,   51,   53,   53,   53,   55,   75,   52,
       75,   55,   55,    0,    0,   56,   50,   53,   53,   56,
       52,   56,    0,   57,   53,   56,   58,   57,   53,   57,
       58,    0,   58,   57,    0,   76,   58,   76,   77,   78,
       77,   78,   79,   80,   79,   80,   81,   82,   81,   82,
       83,    0,   83,   84,    0,   84,   85,    0,   85,   86,
       80,   86,   87,   88,   87,   88,   90,   89,   90,   89,

        0,    0,   91,   81,   91,   95,    0,   82,   83,   85,
       84,   95,   86,   89,   90,   95,   91,   97,   98,   87,
       99,    0,    0,   97,   98,  100,   99,   97,   98,    0,
       99,  100,  101,  102,  103,  100,    0,  103,  101,  102,
      103,  104,  101,  102,  103,    0,  105,  104,  117,  106,
      117,  104,  105,    0,  104,  106,  105,    0,  107,  106,
      108,    0,  105,  106,  107,    0,  108,  109,  107,  108,
      108,  107,  110,  109,  111,    0,  109,  109,  110,    0,
      111,  112,  110,  112,  111,  110,  113,  112,  114,    0,
      113,  112,  113,  118,  114,  118,  113,  119,  114,  119,

      120,    0,  120,  121,  122,  121,  122,  123,    0,  123,
      124,  125,  124,  125,  126,  119,  126,  129,    0,  127,
      122,  127,  128,  129,  128,    0,  120,  129,  121,  141,
      140,  141,  140,    0,    0,  123,  131,  124,  126,  130,
      127,    0,  131,  130,  132,  130,  131,  128,  131,  130,
      132,  133,  134,  133,  132,  132,  140,  133,  134,  135,
        0,  133,  134,    0,  136,  135,  134,  137,    0,  135,
      136,    0,  135,  137,  136,  138,    0,  137,  139,    0,
        0,  138,  138,    0,  139,  138,    0,    0,  139,  139,
      142,  143,  142,  143,  144,  145,  144,  145,  147,  146,

      147,  146,  148,  149,  148,  158,  159,  158,  159,  149,
      143,    0,    0,  149,  145,  149,  142,  150,  160,  151,
      160,  144,  146,  150,  147,  151,    0,  150,  148,  151,
      152,  151,  153,    0,    0,  152,  152,  162,  153,  162,
      152,  154,  153,  155,  156,  153,  154,  154,    0,  155,
      156,  154,  155,  155,  156,  157,  156,  161,    0,  161,
      163,  157,  163,  162,  164,  157,  164,  157,  165,  175,
      165,  175,  166,  167,  168,  161,    0,  163,  166,  167,
      168,  169,  166,  167,  168,  169,  170,  169,  174,  172,
      174,  169,  170,    0,  171,  172,  170,  171,  170,  172,

      171,  173,    0,  176,  171,  176,  177,  173,  180,  178,
      180,  173,  177,    0,  174,  178,  177,    0,  177,  178,
      179,  181,    0,  181,    0,  182,  179,  183,    0,  176,
      179,  182,  179,  183,    0,  182,    0,  183,  185,  185,
      185,  187,  187,  188,  188,  188,  188,  189,  189,  189,
      190,  190,  191,  191,  192,  192,  193,  193,  194,  194,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t eckit_cmd__rule_can_match_eol[55] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static eckit_cmd__state_type eckit_cmd__last_accepting_state;
static char *eckit_cmd__last_accepting_cpos;

extern int eckit_cmd__flex_debug;
int eckit_cmd__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define eckit_cmd_more() eckit_cmd_more_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char eckit_cmd_text[YYLMAX];
char *eckit_cmd_text_ptr;
#line 1 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
#line 2 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"

/*
 * (C) Copyright 1996- ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation
 * nor does it submit to any jurisdiction.
 */

#undef YYLMAX
#define YYLMAX 2048
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "eckit/cmd/CmdParser.h"

static int paren = 0; // Not thread safe, but are lex and yacc safe anyway?

#ifdef __linux__
#define YY_INPUT(buf,result,max_size) { int c = CmdParser::input(); result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); }
#endif


#undef input
#define input()  CmdParser::input()

#undef unput
#define unput(n) CmdParser::unput(n)

#undef output
#define output(n) CmdParser::output(n)

#line 728 "/home/runner/work/eckit/eckit/_codeql_build_dir/src/eckit/cmd/cmdsl.c"

#line 730 "/home/runner/work/eckit/eckit/_codeql_build_dir/src/eckit/cmd/cmdsl.c"

#define INITIAL 0
#define EXPRESSION 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int eckit_cmd__init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int eckit_cmd_lex_destroy ( void );

int eckit_cmd_get_debug ( void );

void eckit_cmd_set_debug ( int debug_flag  );

YY_EXTRA_TYPE eckit_cmd_get_extra ( void );

void eckit_cmd_set_extra ( YY_EXTRA_TYPE user_defined  );

FILE *eckit_cmd_get_in ( void );

void eckit_cmd_set_in  ( FILE * _in_str  );

FILE *eckit_cmd_get_out ( void );

void eckit_cmd_set_out  ( FILE * _out_str  );

			int eckit_cmd_get_leng ( void );

char *eckit_cmd_get_text ( void );

int eckit_cmd_get_lineno ( void );

void eckit_cmd_set_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int eckit_cmd_wrap ( void );
#else
extern int eckit_cmd_wrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void eckit_cmd_unput ( int c, char *buf_ptr  );
    
#endif

#ifndef eckit_cmd_text_ptr
static void eckit_cmd__flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int eckit_cmd__flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int eckit_cmd_input ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( eckit_cmd_text, (size_t) eckit_cmd_leng, 1, eckit_cmd_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->eckit_cmd__is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( eckit_cmd_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( eckit_cmd_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (eckit_cmd__size_t) max_size, eckit_cmd_in)) == 0 && ferror(eckit_cmd_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(eckit_cmd_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "eckit_cmd_terminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef eckit_cmd_terminate
#define eckit_cmd_terminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) eckit_cmd__fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int eckit_cmd_lex (void);

#define YY_DECL int eckit_cmd_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after eckit_cmd_text and eckit_cmd_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	eckit_cmd__state_type eckit_cmd__current_state;
	char *eckit_cmd__cp, *eckit_cmd__bp;
	int eckit_cmd__act;
    
	if ( !(eckit_cmd__init) )
		{
		(eckit_cmd__init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (eckit_cmd__start) )
			(eckit_cmd__start) = 1;	/* first start state */

		if ( ! eckit_cmd_in )
			eckit_cmd_in = stdin;

		if ( ! eckit_cmd_out )
			eckit_cmd_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			eckit_cmd_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				eckit_cmd__create_buffer( eckit_cmd_in, YY_BUF_SIZE );
		}

		eckit_cmd__load_buffer_state(  );
		}

	{
#line 46 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"


#line 951 "/home/runner/work/eckit/eckit/_codeql_build_dir/src/eckit/cmd/cmdsl.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		eckit_cmd__cp = (eckit_cmd__c_buf_p);

		/* Support of eckit_cmd_text. */
		*eckit_cmd__cp = (eckit_cmd__hold_char);

		/* eckit_cmd__bp points to the position in eckit_cmd__ch_buf of the start of
		 * the current run.
		 */
		eckit_cmd__bp = eckit_cmd__cp;

		eckit_cmd__current_state = (eckit_cmd__start);
eckit_cmd__match:
		do
			{
			YY_CHAR eckit_cmd__c = eckit_cmd__ec[YY_SC_TO_UI(*eckit_cmd__cp)] ;
			if ( eckit_cmd__accept[eckit_cmd__current_state] )
				{
				(eckit_cmd__last_accepting_state) = eckit_cmd__current_state;
				(eckit_cmd__last_accepting_cpos) = eckit_cmd__cp;
				}
			while ( eckit_cmd__chk[eckit_cmd__base[eckit_cmd__current_state] + eckit_cmd__c] != eckit_cmd__current_state )
				{
				eckit_cmd__current_state = (int) eckit_cmd__def[eckit_cmd__current_state];
				if ( eckit_cmd__current_state >= 185 )
					eckit_cmd__c = eckit_cmd__meta[eckit_cmd__c];
				}
			eckit_cmd__current_state = eckit_cmd__nxt[eckit_cmd__base[eckit_cmd__current_state] + eckit_cmd__c];
			++eckit_cmd__cp;
			}
		while ( eckit_cmd__base[eckit_cmd__current_state] != 661 );

eckit_cmd__find_action:
		eckit_cmd__act = eckit_cmd__accept[eckit_cmd__current_state];
		if ( eckit_cmd__act == 0 )
			{ /* have to back up */
			eckit_cmd__cp = (eckit_cmd__last_accepting_cpos);
			eckit_cmd__current_state = (eckit_cmd__last_accepting_state);
			eckit_cmd__act = eckit_cmd__accept[eckit_cmd__current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( eckit_cmd__act != YY_END_OF_BUFFER && eckit_cmd__rule_can_match_eol[eckit_cmd__act] )
			{
			int eckit_cmd_l;
			for ( eckit_cmd_l = 0; eckit_cmd_l < eckit_cmd_leng; ++eckit_cmd_l )
				if ( eckit_cmd_text[eckit_cmd_l] == '\n' )
					
    eckit_cmd_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( eckit_cmd__act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*eckit_cmd__cp = (eckit_cmd__hold_char);
			eckit_cmd__cp = (eckit_cmd__last_accepting_cpos);
			eckit_cmd__current_state = (eckit_cmd__last_accepting_state);
			goto eckit_cmd__find_action;

case 1:
YY_RULE_SETUP
#line 48 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{
					eckit_cmd_lval.str = (const char *)eckit_cmd_text+1;
					return PIPE;
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{
					eckit_cmd_lval.str = (const char *)eckit_cmd_text+1;
					return SHELL;
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{
					eckit_cmd_lval.str = (const char *)eckit_cmd_text+1;
					return OUTPUT;
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ paren=1 ; BEGIN EXPRESSION ;     return *eckit_cmd_text ;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ paren++ ;                        return *eckit_cmd_text ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ if(--paren == 0) BEGIN INITIAL ; return *eckit_cmd_text ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return GE ; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return *eckit_cmd_text ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return *eckit_cmd_text ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{
           int c,q = eckit_cmd_text[0];

           eckit_cmd_leng = 0;

           while((c = input()) && c != q && c != '\n')
           {
               if(c == '\\') eckit_cmd_text[eckit_cmd_leng++] = input();
               else eckit_cmd_text[eckit_cmd_leng++] =  c;
            }

            eckit_cmd_text[eckit_cmd_leng++] = 0;
            eckit_cmd_lval.str = (const char *)eckit_cmd_text;
            return STRING;
        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 87 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return AND; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 88 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return AND; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return '='; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 90 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return NE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return GE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return LE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 93 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return NE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 94 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return OR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 95 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return OR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 96 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return NOT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 97 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return NOT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 99 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return MATCH; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 100 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return MATCH; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 102 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return DAY; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 103 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return DAY; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 104 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return MINUTE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 105 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return MINUTE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 106 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return SECOND; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 107 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return SECOND; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 108 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return WEEK; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 109 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return WEEK; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 110 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return MONTH; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 111 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return MONTH; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 112 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return YEAR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 113 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return YEAR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 114 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return HOUR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 115 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return HOUR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return HEXABYTE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 118 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return PETABYTE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return TERABYTE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 120 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return GIGABYTE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 121 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return MEGABYTE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 122 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return KILOBYTE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 123 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return BYTE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return BYTE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 126 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ eckit_cmd_lval.str = (const char *)eckit_cmd_text+1; return OPTION; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 127 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ eckit_cmd_lval.str = (const char *)eckit_cmd_text; return STRING; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 128 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ eckit_cmd_lval.str = (const char *)eckit_cmd_text; return STRING; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 129 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ eckit_cmd_lval.num = Translator<std::string,long long>()((const char *)eckit_cmd_text); return NUMB; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 130 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{
           int c;
           while((c = input()) && (c != '\n'))
                    ;
		   return '\n';
        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 136 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
;
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 137 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return *eckit_cmd_text; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 139 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
{ return *eckit_cmd_text; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 140 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"
ECHO;
	YY_BREAK
#line 1317 "/home/runner/work/eckit/eckit/_codeql_build_dir/src/eckit/cmd/cmdsl.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(EXPRESSION):
	eckit_cmd_terminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int eckit_cmd__amount_of_matched_text = (int) (eckit_cmd__cp - (eckit_cmd_text_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*eckit_cmd__cp = (eckit_cmd__hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed eckit_cmd_in at a new source and called
			 * eckit_cmd_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(eckit_cmd__n_chars) = YY_CURRENT_BUFFER_LVALUE->eckit_cmd__n_chars;
			YY_CURRENT_BUFFER_LVALUE->eckit_cmd__input_file = eckit_cmd_in;
			YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for eckit_cmd__c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since eckit_cmd__c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (eckit_cmd__c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[(eckit_cmd__n_chars)] )
			{ /* This was really a NUL. */
			eckit_cmd__state_type eckit_cmd__next_state;

			(eckit_cmd__c_buf_p) = (eckit_cmd_text_ptr) + eckit_cmd__amount_of_matched_text;

			eckit_cmd__current_state = eckit_cmd__get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * eckit_cmd__get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			eckit_cmd__next_state = eckit_cmd__try_NUL_trans( eckit_cmd__current_state );

			eckit_cmd__bp = (eckit_cmd_text_ptr) + YY_MORE_ADJ;

			if ( eckit_cmd__next_state )
				{
				/* Consume the NUL. */
				eckit_cmd__cp = ++(eckit_cmd__c_buf_p);
				eckit_cmd__current_state = eckit_cmd__next_state;
				goto eckit_cmd__match;
				}

			else
				{
				eckit_cmd__cp = (eckit_cmd__c_buf_p);
				goto eckit_cmd__find_action;
				}
			}

		else switch ( eckit_cmd__get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(eckit_cmd__did_buffer_switch_on_eof) = 0;

				if ( eckit_cmd_wrap(  ) )
					{
					/* Note: because we've taken care in
					 * eckit_cmd__get_next_buffer() to have set up
					 * eckit_cmd_text, we can now set up
					 * eckit_cmd__c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(eckit_cmd__c_buf_p) = (eckit_cmd_text_ptr) + YY_MORE_ADJ;

					eckit_cmd__act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (eckit_cmd__did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(eckit_cmd__c_buf_p) =
					(eckit_cmd_text_ptr) + eckit_cmd__amount_of_matched_text;

				eckit_cmd__current_state = eckit_cmd__get_previous_state(  );

				eckit_cmd__cp = (eckit_cmd__c_buf_p);
				eckit_cmd__bp = (eckit_cmd_text_ptr) + YY_MORE_ADJ;
				goto eckit_cmd__match;

			case EOB_ACT_LAST_MATCH:
				(eckit_cmd__c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[(eckit_cmd__n_chars)];

				eckit_cmd__current_state = eckit_cmd__get_previous_state(  );

				eckit_cmd__cp = (eckit_cmd__c_buf_p);
				eckit_cmd__bp = (eckit_cmd_text_ptr) + YY_MORE_ADJ;
				goto eckit_cmd__find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of eckit_cmd_lex */

/* eckit_cmd__get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int eckit_cmd__get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf;
	char *source = (eckit_cmd_text_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (eckit_cmd__c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[(eckit_cmd__n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->eckit_cmd__fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (eckit_cmd__c_buf_p) - (eckit_cmd_text_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((eckit_cmd__c_buf_p) - (eckit_cmd_text_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__n_chars = (eckit_cmd__n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int eckit_cmd__c_buf_p_offset =
				(int) ((eckit_cmd__c_buf_p) - b->eckit_cmd__ch_buf);

			if ( b->eckit_cmd__is_our_buffer )
				{
				int new_size = b->eckit_cmd__buf_size * 2;

				if ( new_size <= 0 )
					b->eckit_cmd__buf_size += b->eckit_cmd__buf_size / 8;
				else
					b->eckit_cmd__buf_size *= 2;

				b->eckit_cmd__ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					eckit_cmd_realloc( (void *) b->eckit_cmd__ch_buf,
							 (eckit_cmd__size_t) (b->eckit_cmd__buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->eckit_cmd__ch_buf = NULL;

			if ( ! b->eckit_cmd__ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(eckit_cmd__c_buf_p) = &b->eckit_cmd__ch_buf[eckit_cmd__c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[number_to_move]),
			(eckit_cmd__n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__n_chars = (eckit_cmd__n_chars);
		}

	if ( (eckit_cmd__n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			eckit_cmd_restart( eckit_cmd_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((eckit_cmd__n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (eckit_cmd__n_chars) + number_to_move + ((eckit_cmd__n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf = (char *) eckit_cmd_realloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf, (eckit_cmd__size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in eckit_cmd__get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_size = (int) (new_size - 2);
	}

	(eckit_cmd__n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[(eckit_cmd__n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[(eckit_cmd__n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(eckit_cmd_text_ptr) = &YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[0];

	return ret_val;
}

/* eckit_cmd__get_previous_state - get the state just before the EOB char was reached */

    static eckit_cmd__state_type eckit_cmd__get_previous_state (void)
{
	eckit_cmd__state_type eckit_cmd__current_state;
	char *eckit_cmd__cp;
    
	eckit_cmd__current_state = (eckit_cmd__start);

	for ( eckit_cmd__cp = (eckit_cmd_text_ptr) + YY_MORE_ADJ; eckit_cmd__cp < (eckit_cmd__c_buf_p); ++eckit_cmd__cp )
		{
		YY_CHAR eckit_cmd__c = (*eckit_cmd__cp ? eckit_cmd__ec[YY_SC_TO_UI(*eckit_cmd__cp)] : 1);
		if ( eckit_cmd__accept[eckit_cmd__current_state] )
			{
			(eckit_cmd__last_accepting_state) = eckit_cmd__current_state;
			(eckit_cmd__last_accepting_cpos) = eckit_cmd__cp;
			}
		while ( eckit_cmd__chk[eckit_cmd__base[eckit_cmd__current_state] + eckit_cmd__c] != eckit_cmd__current_state )
			{
			eckit_cmd__current_state = (int) eckit_cmd__def[eckit_cmd__current_state];
			if ( eckit_cmd__current_state >= 185 )
				eckit_cmd__c = eckit_cmd__meta[eckit_cmd__c];
			}
		eckit_cmd__current_state = eckit_cmd__nxt[eckit_cmd__base[eckit_cmd__current_state] + eckit_cmd__c];
		}

	return eckit_cmd__current_state;
}

/* eckit_cmd__try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = eckit_cmd__try_NUL_trans( current_state );
 */
    static eckit_cmd__state_type eckit_cmd__try_NUL_trans  (eckit_cmd__state_type eckit_cmd__current_state )
{
	int eckit_cmd__is_jam;
    	char *eckit_cmd__cp = (eckit_cmd__c_buf_p);

	YY_CHAR eckit_cmd__c = 1;
	if ( eckit_cmd__accept[eckit_cmd__current_state] )
		{
		(eckit_cmd__last_accepting_state) = eckit_cmd__current_state;
		(eckit_cmd__last_accepting_cpos) = eckit_cmd__cp;
		}
	while ( eckit_cmd__chk[eckit_cmd__base[eckit_cmd__current_state] + eckit_cmd__c] != eckit_cmd__current_state )
		{
		eckit_cmd__current_state = (int) eckit_cmd__def[eckit_cmd__current_state];
		if ( eckit_cmd__current_state >= 185 )
			eckit_cmd__c = eckit_cmd__meta[eckit_cmd__c];
		}
	eckit_cmd__current_state = eckit_cmd__nxt[eckit_cmd__base[eckit_cmd__current_state] + eckit_cmd__c];
	eckit_cmd__is_jam = (eckit_cmd__current_state == 184);

		return eckit_cmd__is_jam ? 0 : eckit_cmd__current_state;
}

#ifndef YY_NO_UNPUT

    static void eckit_cmd_unput (int c, char * eckit_cmd__bp )
{
	char *eckit_cmd__cp;
    
    eckit_cmd__cp = (eckit_cmd__c_buf_p);

	/* undo effects of setting up eckit_cmd_text */
	*eckit_cmd__cp = (eckit_cmd__hold_char);

	if ( eckit_cmd__cp < YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (eckit_cmd__n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[
					YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf )
			*--dest = *--source;

		eckit_cmd__cp += (int) (dest - source);
		eckit_cmd__bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__n_chars =
			(eckit_cmd__n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_size;

		if ( eckit_cmd__cp < YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--eckit_cmd__cp = (char) c;

    if ( c == '\n' ){
        --eckit_cmd_lineno;
    }

	(eckit_cmd_text_ptr) = eckit_cmd__bp;
	(eckit_cmd__hold_char) = *eckit_cmd__cp;
	(eckit_cmd__c_buf_p) = eckit_cmd__cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int eckit_cmd_input (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(eckit_cmd__c_buf_p) = (eckit_cmd__hold_char);

	if ( *(eckit_cmd__c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* eckit_cmd__c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (eckit_cmd__c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->eckit_cmd__ch_buf[(eckit_cmd__n_chars)] )
			/* This was really a NUL. */
			*(eckit_cmd__c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((eckit_cmd__c_buf_p) - (eckit_cmd_text_ptr));
			++(eckit_cmd__c_buf_p);

			switch ( eckit_cmd__get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because eckit_cmd__g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					eckit_cmd_restart( eckit_cmd_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( eckit_cmd_wrap(  ) )
						return 0;

					if ( ! (eckit_cmd__did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return eckit_cmd_input();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(eckit_cmd__c_buf_p) = (eckit_cmd_text_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (eckit_cmd__c_buf_p);	/* cast for 8-bit char's */
	*(eckit_cmd__c_buf_p) = '\0';	/* preserve eckit_cmd_text */
	(eckit_cmd__hold_char) = *++(eckit_cmd__c_buf_p);

	if ( c == '\n' )
		
    eckit_cmd_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void eckit_cmd_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        eckit_cmd_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            eckit_cmd__create_buffer( eckit_cmd_in, YY_BUF_SIZE );
	}

	eckit_cmd__init_buffer( YY_CURRENT_BUFFER, input_file );
	eckit_cmd__load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void eckit_cmd__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		eckit_cmd_pop_buffer_state();
	 *		eckit_cmd_push_buffer_state(new_buffer);
     */
	eckit_cmd_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(eckit_cmd__c_buf_p) = (eckit_cmd__hold_char);
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_pos = (eckit_cmd__c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__n_chars = (eckit_cmd__n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	eckit_cmd__load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (eckit_cmd_wrap()) processing, but the only time this flag
	 * is looked at is after eckit_cmd_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(eckit_cmd__did_buffer_switch_on_eof) = 1;
}

static void eckit_cmd__load_buffer_state  (void)
{
    	(eckit_cmd__n_chars) = YY_CURRENT_BUFFER_LVALUE->eckit_cmd__n_chars;
	(eckit_cmd_text_ptr) = (eckit_cmd__c_buf_p) = YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_pos;
	eckit_cmd_in = YY_CURRENT_BUFFER_LVALUE->eckit_cmd__input_file;
	(eckit_cmd__hold_char) = *(eckit_cmd__c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE eckit_cmd__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) eckit_cmd_alloc( sizeof( struct eckit_cmd__buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in eckit_cmd__create_buffer()" );

	b->eckit_cmd__buf_size = size;

	/* eckit_cmd__ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->eckit_cmd__ch_buf = (char *) eckit_cmd_alloc( (eckit_cmd__size_t) (b->eckit_cmd__buf_size + 2)  );
	if ( ! b->eckit_cmd__ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in eckit_cmd__create_buffer()" );

	b->eckit_cmd__is_our_buffer = 1;

	eckit_cmd__init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with eckit_cmd__create_buffer()
 * 
 */
    void eckit_cmd__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->eckit_cmd__is_our_buffer )
		eckit_cmd_free( (void *) b->eckit_cmd__ch_buf  );

	eckit_cmd_free( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a eckit_cmd_restart() or at EOF.
 */
    static void eckit_cmd__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	eckit_cmd__flush_buffer( b );

	b->eckit_cmd__input_file = file;
	b->eckit_cmd__fill_buffer = 1;

    /* If b is the current buffer, then eckit_cmd__init_buffer was _probably_
     * called from eckit_cmd_restart() or through eckit_cmd__get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->eckit_cmd__bs_lineno = 1;
        b->eckit_cmd__bs_column = 0;
    }

        b->eckit_cmd__is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void eckit_cmd__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->eckit_cmd__n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->eckit_cmd__ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->eckit_cmd__ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->eckit_cmd__buf_pos = &b->eckit_cmd__ch_buf[0];

	b->eckit_cmd__at_bol = 1;
	b->eckit_cmd__buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		eckit_cmd__load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void eckit_cmd_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	eckit_cmd_ensure_buffer_stack();

	/* This block is copied from eckit_cmd__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(eckit_cmd__c_buf_p) = (eckit_cmd__hold_char);
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__buf_pos = (eckit_cmd__c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->eckit_cmd__n_chars = (eckit_cmd__n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(eckit_cmd__buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from eckit_cmd__switch_to_buffer. */
	eckit_cmd__load_buffer_state(  );
	(eckit_cmd__did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void eckit_cmd_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	eckit_cmd__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((eckit_cmd__buffer_stack_top) > 0)
		--(eckit_cmd__buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		eckit_cmd__load_buffer_state(  );
		(eckit_cmd__did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void eckit_cmd_ensure_buffer_stack (void)
{
	eckit_cmd__size_t num_to_alloc;
    
	if (!(eckit_cmd__buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(eckit_cmd__buffer_stack) = (struct eckit_cmd__buffer_state**)eckit_cmd_alloc
								(num_to_alloc * sizeof(struct eckit_cmd__buffer_state*)
								);
		if ( ! (eckit_cmd__buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in eckit_cmd_ensure_buffer_stack()" );

		memset((eckit_cmd__buffer_stack), 0, num_to_alloc * sizeof(struct eckit_cmd__buffer_state*));

		(eckit_cmd__buffer_stack_max) = num_to_alloc;
		(eckit_cmd__buffer_stack_top) = 0;
		return;
	}

	if ((eckit_cmd__buffer_stack_top) >= ((eckit_cmd__buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		eckit_cmd__size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (eckit_cmd__buffer_stack_max) + grow_size;
		(eckit_cmd__buffer_stack) = (struct eckit_cmd__buffer_state**)eckit_cmd_realloc
								((eckit_cmd__buffer_stack),
								num_to_alloc * sizeof(struct eckit_cmd__buffer_state*)
								);
		if ( ! (eckit_cmd__buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in eckit_cmd_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((eckit_cmd__buffer_stack) + (eckit_cmd__buffer_stack_max), 0, grow_size * sizeof(struct eckit_cmd__buffer_state*));
		(eckit_cmd__buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE eckit_cmd__scan_buffer  (char * base, eckit_cmd__size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) eckit_cmd_alloc( sizeof( struct eckit_cmd__buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in eckit_cmd__scan_buffer()" );

	b->eckit_cmd__buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->eckit_cmd__buf_pos = b->eckit_cmd__ch_buf = base;
	b->eckit_cmd__is_our_buffer = 0;
	b->eckit_cmd__input_file = NULL;
	b->eckit_cmd__n_chars = b->eckit_cmd__buf_size;
	b->eckit_cmd__is_interactive = 0;
	b->eckit_cmd__at_bol = 1;
	b->eckit_cmd__fill_buffer = 0;
	b->eckit_cmd__buffer_status = YY_BUFFER_NEW;

	eckit_cmd__switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to eckit_cmd_lex() will
 * scan from a @e copy of @a str.
 * @param eckit_cmd_str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       eckit_cmd__scan_bytes() instead.
 */
YY_BUFFER_STATE eckit_cmd__scan_string (const char * eckit_cmd_str )
{
    
	return eckit_cmd__scan_bytes( eckit_cmd_str, (int) strlen(eckit_cmd_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to eckit_cmd_lex() will
 * scan from a @e copy of @a bytes.
 * @param eckit_cmd_bytes the byte buffer to scan
 * @param _eckit_cmd_bytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE eckit_cmd__scan_bytes  (const char * eckit_cmd_bytes, int  _eckit_cmd_bytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	eckit_cmd__size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (eckit_cmd__size_t) (_eckit_cmd_bytes_len + 2);
	buf = (char *) eckit_cmd_alloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in eckit_cmd__scan_bytes()" );

	for ( i = 0; i < _eckit_cmd_bytes_len; ++i )
		buf[i] = eckit_cmd_bytes[i];

	buf[_eckit_cmd_bytes_len] = buf[_eckit_cmd_bytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = eckit_cmd__scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in eckit_cmd__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->eckit_cmd__is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void eckit_cmd_noreturn eckit_cmd__fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine eckit_cmd_less() so it works in section 3 code. */

#undef eckit_cmd_less
#define eckit_cmd_less(n) \
	do \
		{ \
		/* Undo effects of setting up eckit_cmd_text. */ \
        int eckit_cmd_less_macro_arg = (n); \
        YY_LESS_LINENO(eckit_cmd_less_macro_arg);\
		eckit_cmd_text[eckit_cmd_leng] = (eckit_cmd__hold_char); \
		(eckit_cmd__c_buf_p) = eckit_cmd_text + eckit_cmd_less_macro_arg; \
		(eckit_cmd__hold_char) = *(eckit_cmd__c_buf_p); \
		*(eckit_cmd__c_buf_p) = '\0'; \
		eckit_cmd_leng = eckit_cmd_less_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int eckit_cmd_get_lineno  (void)
{
    
    return eckit_cmd_lineno;
}

/** Get the input stream.
 * 
 */
FILE *eckit_cmd_get_in  (void)
{
        return eckit_cmd_in;
}

/** Get the output stream.
 * 
 */
FILE *eckit_cmd_get_out  (void)
{
        return eckit_cmd_out;
}

/** Get the length of the current token.
 * 
 */
int eckit_cmd_get_leng  (void)
{
        return eckit_cmd_leng;
}

/** Get the current token.
 * 
 */

char *eckit_cmd_get_text  (void)
{
        return eckit_cmd_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void eckit_cmd_set_lineno (int  _line_number )
{
    
    eckit_cmd_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see eckit_cmd__switch_to_buffer
 */
void eckit_cmd_set_in (FILE *  _in_str )
{
        eckit_cmd_in = _in_str ;
}

void eckit_cmd_set_out (FILE *  _out_str )
{
        eckit_cmd_out = _out_str ;
}

int eckit_cmd_get_debug  (void)
{
        return eckit_cmd__flex_debug;
}

void eckit_cmd_set_debug (int  _bdebug )
{
        eckit_cmd__flex_debug = _bdebug ;
}

static int eckit_cmd__init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from eckit_cmd_lex_destroy(), so don't allocate here.
     */

    /* We do not touch eckit_cmd_lineno unless the option is enabled. */
    eckit_cmd_lineno =  1;
    
    (eckit_cmd__buffer_stack) = NULL;
    (eckit_cmd__buffer_stack_top) = 0;
    (eckit_cmd__buffer_stack_max) = 0;
    (eckit_cmd__c_buf_p) = NULL;
    (eckit_cmd__init) = 0;
    (eckit_cmd__start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    eckit_cmd_in = stdin;
    eckit_cmd_out = stdout;
#else
    eckit_cmd_in = NULL;
    eckit_cmd_out = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * eckit_cmd_lex_init()
     */
    return 0;
}

/* eckit_cmd_lex_destroy is for both reentrant and non-reentrant scanners. */
int eckit_cmd_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		eckit_cmd__delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		eckit_cmd_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	eckit_cmd_free((eckit_cmd__buffer_stack) );
	(eckit_cmd__buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * eckit_cmd_lex() is called, initialization will occur. */
    eckit_cmd__init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef eckit_cmd_text_ptr
static void eckit_cmd__flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int eckit_cmd__flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *eckit_cmd_alloc (eckit_cmd__size_t  size )
{
			return malloc(size);
}

void *eckit_cmd_realloc  (void * ptr, eckit_cmd__size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void eckit_cmd_free (void * ptr )
{
			free( (char *) ptr );	/* see eckit_cmd_realloc() for (char *) cast */
}

#define YYTABLES_NAME "eckit_cmd_tables"

#line 140 "/home/runner/work/eckit/eckit/src/eckit/cmd/cmdsl.l"

    /* "loop"       { return LOOP; } */
    /* "end"        { return END; } */

