repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: check-merge-conflict
- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort
    types_or: [python, cython]
    args: [--line-length=110, --force-single-line-imports, --profile=black]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.8
  hooks:
  - id: ruff
    types: [python]
    exclude: '_\.py$'
    args: [--line-length=110, --fix, --exit-non-zero-on-fix, --preview]
- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.16.6
  hooks:
  - id: cython-lint
    types: [cython]
  - id: double-quote-cython-strings
    types: [cython]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.7
  hooks:
  - id: clang-format
    types: [c, c++]
    exclude: 'src/_eckit/_.*.(h|cpp)'
