# CMake generated Testfile for 
# Source directory: /home/runner/work/eckit/eckit/tests/filesystem
# Build directory: /home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(eckit_test_filesystem_aiohandle "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_aiohandle")
set_tests_properties(eckit_test_filesystem_aiohandle PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;6;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_asynchandle "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_asynchandle")
set_tests_properties(eckit_test_filesystem_asynchandle PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;11;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_atomic_file_update "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_atomic_file_update")
set_tests_properties(eckit_test_filesystem_atomic_file_update PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;15;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_localpathname "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_localpathname")
set_tests_properties(eckit_test_filesystem_localpathname PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;20;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_restarthandle "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_restarthandle")
set_tests_properties(eckit_test_filesystem_restarthandle PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;26;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_pathexpander "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_pathexpander")
set_tests_properties(eckit_test_filesystem_pathexpander PROPERTIES  ENVIRONMENT "CURRENT_TEST_DIR=/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem;OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;30;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_filemode "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_filemode")
set_tests_properties(eckit_test_filesystem_filemode PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;35;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_uri "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_uri")
set_tests_properties(eckit_test_filesystem_uri PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;39;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_pathname "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_pathname")
set_tests_properties(eckit_test_pathname PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;43;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
add_test(eckit_test_filesystem_filespace_strategies "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/filesystem/eckit_test_filesystem_filespace_strategies")
set_tests_properties(eckit_test_filesystem_filespace_strategies PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;47;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/filesystem/CMakeLists.txt;0;")
