# CMake generated Testfile for 
# Source directory: /home/runner/work/eckit/eckit/tests/value
# Build directory: /home/runner/work/eckit/eckit/_codeql_build_dir/tests/value
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(eckit_test_value_value_params "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_params")
set_tests_properties(eckit_test_value_value_params PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;10;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_properties "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_properties")
set_tests_properties(eckit_test_value_value_properties PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;14;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_const "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_const")
set_tests_properties(eckit_test_value_value_const PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;18;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_typeordering "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_typeordering")
set_tests_properties(eckit_test_value_value_typeordering PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;22;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_nil "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_nil")
set_tests_properties(eckit_test_value_value_nil PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_boolean "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_boolean")
set_tests_properties(eckit_test_value_value_boolean PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_integer "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_integer")
set_tests_properties(eckit_test_value_value_integer PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_double "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_double")
set_tests_properties(eckit_test_value_value_double PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_string "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_string")
set_tests_properties(eckit_test_value_value_string PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_valuemap "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_valuemap")
set_tests_properties(eckit_test_value_value_valuemap PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_valuelist "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_valuelist")
set_tests_properties(eckit_test_value_value_valuelist PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_date "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_date")
set_tests_properties(eckit_test_value_value_date PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
add_test(eckit_test_value_value_orderedmap "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/value/eckit_test_value_value_orderedmap")
set_tests_properties(eckit_test_value_value_orderedmap PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;27;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/value/CMakeLists.txt;0;")
