# CMake generated Testfile for 
# Source directory: /home/runner/work/eckit/eckit/tests/linalg
# Build directory: /home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(eckit_test_linalg_factory "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_factory" "--log_level=message")
set_tests_properties(eckit_test_linalg_factory PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;9;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_dense_backend "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_dense_backend" "--log_level=message")
set_tests_properties(eckit_test_linalg_dense_backend PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;14;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_sparse_backend "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_sparse_backend" "--log_level=message")
set_tests_properties(eckit_test_linalg_sparse_backend PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;19;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_matrix "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_matrix" "--log_level=message")
set_tests_properties(eckit_test_linalg_matrix PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;24;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_tensor "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_tensor" "--log_level=message")
set_tests_properties(eckit_test_linalg_tensor PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;29;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_mixed_backend "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_mixed_backend" "--log_level=message")
set_tests_properties(eckit_test_linalg_mixed_backend PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;35;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_mixed_backend_generic "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_mixed_backend" "--log_level=message" "-linearAlgebraBackend" "generic")
set_tests_properties(eckit_test_linalg_mixed_backend_generic PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;40;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_dense_backend_generic "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_dense_backend" "--log_level=message" "-linearAlgebraDenseBackend" "generic")
set_tests_properties(eckit_test_linalg_dense_backend_generic PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;71;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_sparse_backend_generic "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_sparse_backend" "--log_level=message" "-linearAlgebraSparseBackend" "generic")
set_tests_properties(eckit_test_linalg_sparse_backend_generic PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;104;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_sparse "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_sparse" "--log_level=message")
set_tests_properties(eckit_test_linalg_sparse PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;137;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
add_test(eckit_test_linalg_streaming "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/linalg/eckit_test_linalg_streaming" "--log_level=message")
set_tests_properties(eckit_test_linalg_streaming PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;142;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/linalg/CMakeLists.txt;0;")
