# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS eckit eckit_cmd eckit_sql eckit_distributed eckit_geometry eckit_linalg eckit_maths eckit_mpi eckit_option eckit_web eckit_codec eckit_spec eckit_geo eckit_version eckit_info eckit_fraction eckit_codec_list eckit_area_list eckit_gaussian_latitudes eckit_grid eckit_grid_list eckit_grid_nearest eckit_grid_spec)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target eckit
add_library(eckit SHARED IMPORTED)

set_target_properties(eckit PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/eckit/eckit/_codeql_build_dir/src;/home/runner/work/eckit/eckit/src"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/librt.a;dl"
)

# Create imported target eckit_cmd
add_library(eckit_cmd SHARED IMPORTED)

set_target_properties(eckit_cmd PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_sql
add_library(eckit_sql SHARED IMPORTED)

set_target_properties(eckit_sql PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_distributed
add_library(eckit_distributed SHARED IMPORTED)

set_target_properties(eckit_distributed PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_geometry
add_library(eckit_geometry SHARED IMPORTED)

set_target_properties(eckit_geometry PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_linalg
add_library(eckit_linalg SHARED IMPORTED)

set_target_properties(eckit_linalg PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_maths
add_library(eckit_maths SHARED IMPORTED)

set_target_properties(eckit_maths PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_mpi
add_library(eckit_mpi SHARED IMPORTED)

set_target_properties(eckit_mpi PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_option
add_library(eckit_option SHARED IMPORTED)

set_target_properties(eckit_option PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_web
add_library(eckit_web SHARED IMPORTED)

set_target_properties(eckit_web PROPERTIES
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_codec
add_library(eckit_codec SHARED IMPORTED)

set_target_properties(eckit_codec PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/eckit/eckit/src;/home/runner/work/eckit/eckit/_codeql_build_dir/src"
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_spec
add_library(eckit_spec SHARED IMPORTED)

set_target_properties(eckit_spec PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/eckit/eckit/src;/home/runner/work/eckit/eckit/_codeql_build_dir/src"
  INTERFACE_LINK_LIBRARIES "eckit"
)

# Create imported target eckit_geo
add_library(eckit_geo SHARED IMPORTED)

set_target_properties(eckit_geo PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/eckit/eckit/src;/home/runner/work/eckit/eckit/_codeql_build_dir/src"
  INTERFACE_LINK_LIBRARIES "eckit_maths;eckit_spec;eckit_codec"
)

# Create imported target eckit_version
add_executable(eckit_version IMPORTED)

# Create imported target eckit_info
add_executable(eckit_info IMPORTED)

# Create imported target eckit_fraction
add_executable(eckit_fraction IMPORTED)

# Create imported target eckit_codec_list
add_executable(eckit_codec_list IMPORTED)

# Create imported target eckit_area_list
add_executable(eckit_area_list IMPORTED)

# Create imported target eckit_gaussian_latitudes
add_executable(eckit_gaussian_latitudes IMPORTED)

# Create imported target eckit_grid
add_executable(eckit_grid IMPORTED)

# Create imported target eckit_grid_list
add_executable(eckit_grid_list IMPORTED)

# Create imported target eckit_grid_nearest
add_executable(eckit_grid_nearest IMPORTED)

# Create imported target eckit_grid_spec
add_executable(eckit_grid_spec IMPORTED)

# Import target "eckit" for configuration "Release"
set_property(TARGET eckit APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit.so"
  IMPORTED_SONAME_RELEASE "libeckit.so"
  )

# Import target "eckit_cmd" for configuration "Release"
set_property(TARGET eckit_cmd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_cmd PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_cmd.so"
  IMPORTED_SONAME_RELEASE "libeckit_cmd.so"
  )

# Import target "eckit_sql" for configuration "Release"
set_property(TARGET eckit_sql APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_sql PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_sql.so"
  IMPORTED_SONAME_RELEASE "libeckit_sql.so"
  )

# Import target "eckit_distributed" for configuration "Release"
set_property(TARGET eckit_distributed APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_distributed PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_distributed.so"
  IMPORTED_SONAME_RELEASE "libeckit_distributed.so"
  )

# Import target "eckit_geometry" for configuration "Release"
set_property(TARGET eckit_geometry APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_geometry PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_geometry.so"
  IMPORTED_SONAME_RELEASE "libeckit_geometry.so"
  )

# Import target "eckit_linalg" for configuration "Release"
set_property(TARGET eckit_linalg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_linalg PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_linalg.so"
  IMPORTED_SONAME_RELEASE "libeckit_linalg.so"
  )

# Import target "eckit_maths" for configuration "Release"
set_property(TARGET eckit_maths APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_maths PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_maths.so"
  IMPORTED_SONAME_RELEASE "libeckit_maths.so"
  )

# Import target "eckit_mpi" for configuration "Release"
set_property(TARGET eckit_mpi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_mpi PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_mpi.so"
  IMPORTED_SONAME_RELEASE "libeckit_mpi.so"
  )

# Import target "eckit_option" for configuration "Release"
set_property(TARGET eckit_option APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_option PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_option.so"
  IMPORTED_SONAME_RELEASE "libeckit_option.so"
  )

# Import target "eckit_web" for configuration "Release"
set_property(TARGET eckit_web APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_web PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_web.so"
  IMPORTED_SONAME_RELEASE "libeckit_web.so"
  )

# Import target "eckit_codec" for configuration "Release"
set_property(TARGET eckit_codec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_codec PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_codec.so"
  IMPORTED_SONAME_RELEASE "libeckit_codec.so"
  )

# Import target "eckit_spec" for configuration "Release"
set_property(TARGET eckit_spec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_spec PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_spec.so"
  IMPORTED_SONAME_RELEASE "libeckit_spec.so"
  )

# Import target "eckit_geo" for configuration "Release"
set_property(TARGET eckit_geo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_geo PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/lib/libeckit_geo.so"
  IMPORTED_SONAME_RELEASE "libeckit_geo.so"
  )

# Import target "eckit_version" for configuration "Release"
set_property(TARGET eckit_version APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_version PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-version"
  )

# Import target "eckit_info" for configuration "Release"
set_property(TARGET eckit_info APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_info PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-info"
  )

# Import target "eckit_fraction" for configuration "Release"
set_property(TARGET eckit_fraction APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_fraction PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-fraction"
  )

# Import target "eckit_codec_list" for configuration "Release"
set_property(TARGET eckit_codec_list APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_codec_list PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-codec-list"
  )

# Import target "eckit_area_list" for configuration "Release"
set_property(TARGET eckit_area_list APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_area_list PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-area-list"
  )

# Import target "eckit_gaussian_latitudes" for configuration "Release"
set_property(TARGET eckit_gaussian_latitudes APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_gaussian_latitudes PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-gaussian-latitudes"
  )

# Import target "eckit_grid" for configuration "Release"
set_property(TARGET eckit_grid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_grid PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-grid"
  )

# Import target "eckit_grid_list" for configuration "Release"
set_property(TARGET eckit_grid_list APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_grid_list PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-grid-list"
  )

# Import target "eckit_grid_nearest" for configuration "Release"
set_property(TARGET eckit_grid_nearest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_grid_nearest PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-grid-nearest"
  )

# Import target "eckit_grid_spec" for configuration "Release"
set_property(TARGET eckit_grid_spec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(eckit_grid_spec PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/runner/work/eckit/eckit/_codeql_build_dir/bin/eckit-grid-spec"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
