# CMake generated Testfile for 
# Source directory: /home/runner/work/eckit/eckit/tests/maths
# Build directory: /home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(eckit_test_maths_fraction "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths/eckit_test_maths_fraction")
set_tests_properties(eckit_test_maths_fraction PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;9;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_matrix "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths/eckit_test_maths_matrix")
set_tests_properties(eckit_test_maths_matrix PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;9;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_matrix3 "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths/eckit_test_maths_matrix3")
set_tests_properties(eckit_test_maths_matrix3 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;9;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_floating_point_exceptions "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths/eckit_test_maths_floating_point_exceptions")
set_tests_properties(eckit_test_maths_floating_point_exceptions PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;executable" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;470;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;16;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_floating_point_exception_FE_INVALID "/home/runner/work/eckit/eckit/tests/maths/floating_point_exception.sh" "FE_INVALID")
set_tests_properties(eckit_test_maths_floating_point_exception_FE_INVALID PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" WORKING_DIRECTORY "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;41;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_floating_point_exception_FE_INEXACT "/home/runner/work/eckit/eckit/tests/maths/floating_point_exception.sh" "FE_INEXACT")
set_tests_properties(eckit_test_maths_floating_point_exception_FE_INEXACT PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" WORKING_DIRECTORY "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;41;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_floating_point_exception_FE_DIVBYZERO "/home/runner/work/eckit/eckit/tests/maths/floating_point_exception.sh" "FE_DIVBYZERO")
set_tests_properties(eckit_test_maths_floating_point_exception_FE_DIVBYZERO PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" WORKING_DIRECTORY "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;41;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_floating_point_exception_FE_OVERFLOW "/home/runner/work/eckit/eckit/tests/maths/floating_point_exception.sh" "FE_OVERFLOW")
set_tests_properties(eckit_test_maths_floating_point_exception_FE_OVERFLOW PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" WORKING_DIRECTORY "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;41;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
add_test(eckit_test_maths_floating_point_exception_FE_UNDERFLOW "/home/runner/work/eckit/eckit/tests/maths/floating_point_exception.sh" "FE_UNDERFLOW")
set_tests_properties(eckit_test_maths_floating_point_exception_FE_UNDERFLOW PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "eckit;script" WORKING_DIRECTORY "/home/runner/work/eckit/eckit/_codeql_build_dir/tests/maths" _BACKTRACE_TRIPLES "/home/runner/work/eckit/ecbuild/cmake/ecbuild_add_test.cmake;468;add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;41;ecbuild_add_test;/home/runner/work/eckit/eckit/tests/maths/CMakeLists.txt;0;")
