[workspace]
resolver = "2"
members = ["crates/eckit-sys", "crates/eckit"]

[workspace.package]
version = "2.2.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/ecmwf/eckit"
rust-version = "1.90"
readme = "README.md"
keywords = ["ecmwf", "weather", "meteorology", "geo"]
categories = ["science"]

[workspace.dependencies]
# Internal
eckit-sys = { version = "2.2", path = "crates/eckit-sys" }
eckit = { version = "2.2", path = "crates/eckit" }

# Build tools
bindman = "0.2"
bindman-build = "0.2"
bindman-utils = "0.2"

# External
cxx = "1.0"
cxx-build = "1.0"
log = "0.4"
thiserror = "2"
tempfile = "3"
