// SPDX-FileCopyrightText: 1996- European Centre for Medium-Range Weather Forecasts (ECMWF)
// SPDX-License-Identifier: Apache-2.0

/// @author Tiago Quintino
///
/// @note Include this header for accessing build time configurations detected by the build system
///       introspection.

#ifndef eckit_eckit_h
#define eckit_eckit_h

#include "eckit/eckit_config.h"  // configuration header auto-generated by build system

//--------------------------------------------------------------------------------------------------

#if (!eckit_HAVE_MAP_ANONYMOUS) && eckit_HAVE_MAP_ANON
#define MAP_ANONYMOUS MAP_ANON
#endif

/* Usefull macros */

#ifndef NUMBER
#define NUMBER(x) (sizeof(x) / sizeof(x[0]))
#endif

//--------------------------------------------------------------------------------------------------

#endif
