# SPDX-FileCopyrightText: 1996- European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0


name: Build Python Wrapper Wheel

on:
  # Trigger the workflow manually
  workflow_dispatch:
    inputs:
      use_test_pypi:
        description: Use test pypi instead of the regular one
        required: false
        type: boolean
        default: false

  # Allow to be called from another workflow -- eg `cd.yml`
  workflow_call:
    inputs:
      use_test_pypi:
        description: Use test pypi instead of the regular one
        required: false
        type: boolean
        default: false

jobs:
  python-wrapper-wheel:
    name: Python Wrapper Wheel
    uses: ecmwf/reusable-workflows/.github/workflows/python-wrapper-wheel.yml@main
    with:
      wheel_directory: python/eckitlib
      use_test_pypi: ${{ inputs.use_test_pypi }}
    secrets: inherit
