name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger on public pull request approval
  pull_request_target:
    types: [labeled]

  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  # Run CI including downstream packages on self-hosted runners
  downstream-ci:
    name: downstream-ci
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    uses: ecmwf-actions/downstream-ci/.github/workflows/downstream-ci.yml@main
    with:
      eckit: ecmwf/eckit@${{ github.event.pull_request.head.sha || github.sha }}
      skip_matrix_jobs: |
        gnu@debian-11
        gnu-7@centos-7.9
        gnu-8@centos-7.9
        gnu@rocky-8.6
        clang@rocky-8.6
        gnu@ubuntu-22.04
        gnu@fedora-37
      codecov_upload: true
    secrets: inherit

  # Run CI of private downstream packages on self-hosted runners
  private-downstream-ci:
    name: private-downstream-ci
    needs: [downstream-ci]
    if: (success() || failure()) && ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Dispatch private downstream CI
        uses: ecmwf-actions/dispatch-private-downstream-ci@v1
        with:
          token: ${{ secrets.GH_REPO_READ_TOKEN }}
          owner: ecmwf-actions
          repository: private-downstream-ci
          event_type: downstream-ci
          payload: '{"eckit": "ecmwf/eckit@${{ github.event.pull_request.head.sha || github.sha }}"}'
