name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - "master"
      - "develop"
    tags-ignore:
      - "**"

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger on public pull request approval
  pull_request_target:
    types: [labeled]

  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  # Run CI including downstream packages on self-hosted runners
  downstream-ci:
    name: downstream-ci
    if: ${{ !github.event.pull_request.head.repo.fork && (github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci') }}
    uses: ecmwf-actions/downstream-ci/.github/workflows/downstream-ci.yml@main
    with:
      eckit: ecmwf/eckit@${{ github.event.pull_request.head.sha || github.sha }}
      gribjump: ecmwf/gribjump@debug/ci
    secrets: inherit

  # Run CI of private downstream packages on HPC
  notify:
    runs-on: ubuntu-latest
    needs:
      - downstream-ci
    if: ${{ always() && !github.event.pull_request.head.repo.fork && (github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci') }}
    steps:
      - name: Trigger Teams notification
        if: failure() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: ecmwf-actions/notify-teams@v1
        with:
          incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
          needs_context: ${{ toJSON(needs) }}
          notify_on: |
            failure
